import csv
import json
import math
from collections import defaultdict
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT_CSV = ROOT / "prices" / "all_countries.csv"
OUTPUT_JSON = ROOT / "data" / "negative_prices.json"
OUTPUT_JS = ROOT / "data" / "negative_prices.js"
SPOT_OUTPUT_JSON = ROOT / "data" / "spot_prices.json"
SPOT_OUTPUT_JS = ROOT / "data" / "spot_prices.js"
PROFILE_OUTPUT_JSON = ROOT / "data" / "generation_profiles.json"
PROFILE_OUTPUT_JS = ROOT / "data" / "generation_profiles.js"


def parse_local_datetime(value):
    return datetime.strptime(value, "%Y-%m-%d %H:%M:%S")


def normalize(values):
    total = sum(values)
    return [value / total if total else 0 for value in values]


def solar_profile(month):
    daylight = {
        1: (8.0, 16.4), 2: (7.3, 17.3), 3: (6.5, 18.2), 4: (5.9, 19.1),
        5: (5.3, 20.0), 6: (5.0, 20.7), 7: (5.1, 20.6), 8: (5.8, 19.8),
        9: (6.4, 18.8), 10: (7.0, 17.7), 11: (7.6, 16.6), 12: (8.1, 16.1),
    }
    sunrise, sunset = daylight[month]
    shape = 1.35 if month in {5, 6, 7, 8} else 1.55
    values = []
    for hour in range(24):
      midpoint = hour + 0.5
      if midpoint <= sunrise or midpoint >= sunset:
          values.append(0.0)
      else:
          progress = (midpoint - sunrise) / (sunset - sunrise)
          values.append(math.sin(math.pi * progress) ** shape)
    return normalize(values)


def wind_onshore_profile(month):
    winter_factor = {
        1: 1.10, 2: 1.08, 3: 1.04, 4: 0.98, 5: 0.94, 6: 0.90,
        7: 0.88, 8: 0.90, 9: 0.96, 10: 1.02, 11: 1.08, 12: 1.12,
    }[month]
    values = []
    for hour in range(24):
        night_bump = 0.06 * math.cos((hour - 2) / 24 * 2 * math.pi)
        evening_bump = 0.025 * math.cos((hour - 21) / 24 * 2 * math.pi)
        values.append(max(0.01, winter_factor + night_bump + evening_bump))
    return normalize(values)


def generation_profiles_payload():
    technologies = {
        "solar_pv": {
            "label": "Solar PV",
            "description": "Synthetic monthly hourly photovoltaic generation profile, normalized so each month sums to 1 across 24 hours.",
            "months": {},
        },
        "wind_onshore": {
            "label": "Wind onshore",
            "description": "Synthetic monthly hourly wind generation profile, normalized so each month sums to 1 across 24 hours.",
            "months": {},
        },
    }
    for month in range(1, 13):
        key = f"{month:02d}"
        technologies["solar_pv"]["months"][key] = solar_profile(month)
        technologies["wind_onshore"]["months"][key] = wind_onshore_profile(month)
    return {
        "source": "synthetic profiles generated by scripts/build_negative_prices.py",
        "normalization": "Each technology-month profile contains 24 hourly weights that sum to 1.",
        "technologies": technologies,
    }


def main():
    if not INPUT_CSV.exists():
        raise FileNotFoundError(f"Input CSV not found: {INPUT_CSV}")

    countries = {}
    months_by_country = defaultdict(set)
    negative_by_day = defaultdict(lambda: defaultdict(int))
    negative_by_hour = defaultdict(lambda: defaultdict(int))
    consecutive_by_day = defaultdict(lambda: defaultdict(int))
    current_negative_streak = defaultdict(int)
    observed_days_by_month = defaultdict(set)
    spot_year = defaultdict(lambda: {"sum": 0.0, "count": 0})
    spot_month = defaultdict(lambda: {"sum": 0.0, "count": 0})
    spot_day = defaultdict(lambda: {"sum": 0.0, "count": 0, "min": None, "max": None})
    spot_hour = defaultdict(lambda: {"sum": 0.0, "count": 0})
    total_observations = 0
    total_negative = 0
    skipped_rows = 0
    latest_local_date = None

    with INPUT_CSV.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)

        for row in reader:
            country = row["Country"].strip()
            iso3 = row["ISO3 Code"].strip()
            try:
                local_dt = parse_local_datetime(row["Datetime (Local)"].strip())
                price = float(row["Price (EUR/MWhe)"])
            except (KeyError, TypeError, ValueError):
                skipped_rows += 1
                continue

            month_key = local_dt.strftime("%Y-%m")
            year_key = local_dt.strftime("%Y")
            day_key = str(local_dt.day)
            date_key = local_dt.strftime("%Y-%m-%d")

            countries[country] = iso3
            months_by_country[country].add(month_key)
            observed_days_by_month[(country, month_key)].add(day_key)
            if latest_local_date is None or local_dt.date() > latest_local_date:
                latest_local_date = local_dt.date()
            total_observations += 1
            spot_year[(country, year_key)]["sum"] += price
            spot_year[(country, year_key)]["count"] += 1
            spot_month[(country, month_key)]["sum"] += price
            spot_month[(country, month_key)]["count"] += 1
            spot_day[(country, month_key, day_key)]["sum"] += price
            spot_day[(country, month_key, day_key)]["count"] += 1
            spot_hour[(country, month_key, local_dt.hour)]["sum"] += price
            spot_hour[(country, month_key, local_dt.hour)]["count"] += 1
            if spot_day[(country, month_key, day_key)]["min"] is None or price < spot_day[(country, month_key, day_key)]["min"]:
                spot_day[(country, month_key, day_key)]["min"] = price
            if spot_day[(country, month_key, day_key)]["max"] is None or price > spot_day[(country, month_key, day_key)]["max"]:
                spot_day[(country, month_key, day_key)]["max"] = price

            if price < 0:
                negative_by_day[(country, month_key)][day_key] += 1
                negative_by_hour[(country, month_key)][str(local_dt.hour)] += 1
                current_negative_streak[(country, date_key)] += 1
                consecutive_by_day[(country, month_key)][day_key] = max(
                    consecutive_by_day[(country, month_key)][day_key],
                    current_negative_streak[(country, date_key)],
                )
                total_negative += 1
            else:
                current_negative_streak[(country, date_key)] = 0

    series = {}
    for country, months in months_by_country.items():
        series[country] = {}
        for month_key in sorted(months):
            year, month = map(int, month_key.split("-"))
            if month == 12:
                next_month = datetime(year + 1, 1, 1)
            else:
                next_month = datetime(year, month + 1, 1)
            current_month = datetime(year, month, 1)
            days_in_month = (next_month - current_month).days

            days = []
            cumulative = 0
            counts = negative_by_day[(country, month_key)]
            hourly_counts = negative_by_hour[(country, month_key)]
            consecutive_counts = consecutive_by_day[(country, month_key)]
            for day in range(1, days_in_month + 1):
                negatives = counts.get(str(day), 0)
                cumulative += negatives
                days.append(
                    {
                        "day": day,
                        "negativePrices": negatives,
                        "maxConsecutiveNegativePrices": consecutive_counts.get(str(day), 0),
                        "otherNegativePrices": max(
                            0,
                            negatives - consecutive_counts.get(str(day), 0),
                        ),
                        "cumulativeNegativePrices": cumulative,
                    }
                )

            observed_days = len(observed_days_by_month[(country, month_key)])
            series[country][month_key] = {
                "days": days,
                "daysInMonth": days_in_month,
                "observedDays": observed_days,
                "isCompleteMonth": observed_days == days_in_month,
                "hourlyNegativePrices": [
                    hourly_counts.get(str(hour), 0)
                    for hour in range(24)
                ],
                "totalNegativePrices": cumulative,
                "daysWithNegativePrices": sum(1 for item in days if item["negativePrices"] > 0),
                "maxConsecutiveNegativePrices": max(
                    (item["maxConsecutiveNegativePrices"] for item in days),
                    default=0,
                ),
            }

    payload = {
        "source": str(INPUT_CSV.relative_to(ROOT)).replace("\\", "/"),
        "generatedFromRows": total_observations,
        "skippedRows": skipped_rows,
        "totalNegativePrices": total_negative,
        "latestLocalDate": latest_local_date.isoformat() if latest_local_date else None,
        "countries": [
            {
                "name": country,
                "iso3": countries[country],
                "months": sorted(months_by_country[country]),
            }
            for country in sorted(countries)
        ],
        "series": series,
    }

    spot_series = {}
    for country, months in months_by_country.items():
        years = sorted({month[:4] for month in months})
        spot_series[country] = {"years": {}}
        for year in years:
            year_bucket = spot_year[(country, year)]
            year_average = year_bucket["sum"] / year_bucket["count"] if year_bucket["count"] else None
            year_spreads = []
            spot_series[country]["years"][year] = {
                "averagePrice": year_average,
                "observations": year_bucket["count"],
                "averageDailySpread": None,
                "months": {},
            }

            for month_key in sorted(month for month in months if month.startswith(f"{year}-")):
                month_bucket = spot_month[(country, month_key)]
                month_average = month_bucket["sum"] / month_bucket["count"] if month_bucket["count"] else None
                month_spreads = []
                month_number = int(month_key[5:7])
                next_month = datetime(int(year) + (1 if month_number == 12 else 0), 1 if month_number == 12 else month_number + 1, 1)
                current_month = datetime(int(year), month_number, 1)
                days_in_month = (next_month - current_month).days

                days = []
                hourly_average_prices = []
                for hour in range(24):
                    hour_bucket = spot_hour[(country, month_key, hour)]
                    hourly_average_prices.append(
                        hour_bucket["sum"] / hour_bucket["count"] if hour_bucket["count"] else None
                    )

                for day in range(1, days_in_month + 1):
                    day_bucket = spot_day[(country, month_key, str(day))]
                    average = day_bucket["sum"] / day_bucket["count"] if day_bucket["count"] else None
                    spread = (
                        day_bucket["max"] - day_bucket["min"]
                        if day_bucket["count"] and day_bucket["min"] is not None and day_bucket["max"] is not None
                        else None
                    )
                    if spread is not None:
                        month_spreads.append(spread)
                        year_spreads.append(spread)
                    days.append(
                        {
                            "day": day,
                            "averagePrice": average,
                            "minPrice": day_bucket["min"],
                            "maxPrice": day_bucket["max"],
                            "dailySpread": spread,
                            "observations": day_bucket["count"],
                        }
                    )

                spot_series[country]["years"][year]["months"][month_key] = {
                    "averagePrice": month_average,
                    "averageDailySpread": sum(month_spreads) / len(month_spreads) if month_spreads else None,
                    "observations": month_bucket["count"],
                    "hourlyAveragePrices": hourly_average_prices,
                    "days": days,
                }

            spot_series[country]["years"][year]["averageDailySpread"] = (
                sum(year_spreads) / len(year_spreads) if year_spreads else None
            )

    spot_payload = {
        "source": str(INPUT_CSV.relative_to(ROOT)).replace("\\", "/"),
        "generatedFromRows": total_observations,
        "skippedRows": skipped_rows,
        "latestLocalDate": latest_local_date.isoformat() if latest_local_date else None,
        "countries": [
            {
                "name": country,
                "iso3": countries[country],
                "years": sorted({month[:4] for month in months_by_country[country]}),
            }
            for country in sorted(countries)
        ],
        "series": spot_series,
    }
    profile_payload = generation_profiles_payload()

    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_JSON.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)

    with OUTPUT_JS.open("w", encoding="utf-8") as handle:
        handle.write("window.NEGATIVE_PRICE_DATA = ")
        json.dump(payload, handle, ensure_ascii=False)
        handle.write(";\n")

    with SPOT_OUTPUT_JSON.open("w", encoding="utf-8") as handle:
        json.dump(spot_payload, handle, ensure_ascii=False, indent=2)

    with SPOT_OUTPUT_JS.open("w", encoding="utf-8") as handle:
        handle.write("window.SPOT_PRICE_DATA = ")
        json.dump(spot_payload, handle, ensure_ascii=False)
        handle.write(";\n")

    with PROFILE_OUTPUT_JSON.open("w", encoding="utf-8") as handle:
        json.dump(profile_payload, handle, ensure_ascii=False, indent=2)

    with PROFILE_OUTPUT_JS.open("w", encoding="utf-8") as handle:
        handle.write("window.GENERATION_PROFILE_DATA = ")
        json.dump(profile_payload, handle, ensure_ascii=False)
        handle.write(";\n")

    print(f"Wrote {OUTPUT_JSON}")
    print(f"Wrote {OUTPUT_JS}")
    print(f"Wrote {SPOT_OUTPUT_JSON}")
    print(f"Wrote {SPOT_OUTPUT_JS}")
    print(f"Wrote {PROFILE_OUTPUT_JSON}")
    print(f"Wrote {PROFILE_OUTPUT_JS}")
    print(f"Rows processed: {total_observations:,}")
    print(f"Rows skipped: {skipped_rows:,}")
    print(f"Negative prices: {total_negative:,}")


if __name__ == "__main__":
    main()
